name: 🧪

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  run-tests-rust:
    name: Run Rust tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ["stable"]
        mpi: ['mpich', 'openmpi']
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: Install cargo-mpirun
        run: cargo install cargo-mpirun
      - uses: actions/checkout@v4

      - name: Run unit tests
        run: cargo test
      - name: Run unit tests in release mode
        run: cargo test --release
      - name: Run tests
        run: cargo test --examples --release
      - name: Run examples
        run: |
          python3 find_examples.py
          chmod +x examples.sh
          ./examples.sh

  check-dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ["stable"]
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Install cargo-upgrades
        run: cargo install cargo-upgrades
      - uses: actions/checkout@v4
      # - name: Check that dependencies are up to date
      #   run:
      #     cargo upgrades
